export const CATEGORY_SELECT = "SELECTED_IMAGE_CATEGORY";

// authentication
export const AUTHENTICATION_SUCCESS = "AUTHENTICATION_SUCCESS_FROM_FIREBASE";
export const AUTHENTICATION_FAILED = "AUTHENTICATION_FAILED_FROM_FIREBASE";
export const AUTHENTICATION_LOADING = "AUTHENTICATION_LOADING_FROM_FIREBASE";
export const AUTHENTICATION_LOGOUT = "AUTHENTICATION_LOGOUT_FROM_FIREBASE";
export const API_KEY = "AIzaSyCJCkAm_JwkzdTTxUPfP0N-BhcySiF-VlQ";

export const ADD_COMMENT = "ADD_NEW_COMMENT";
export const ADD_COMMENT_FAILED = "FAILED_TO_ADD_NEW_COMMENT";
export const LOAD_COMMENT = "LOAD_COMMENT_FROM_FIREBASE";
export const LOAD_COMMENT_FAILED = "LOAD_COMMENT_FAILED_FROM_FIREBASE";